/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { THE_NYX_WEAVE_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';

export const WITHDRAW_ALL_TOKENS_FROM_TREASURY_DISCRIMINATOR = new Uint8Array([
  179, 239, 112, 0, 91, 19, 179, 143,
]);

export function getWithdrawAllTokensFromTreasuryDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    WITHDRAW_ALL_TOKENS_FROM_TREASURY_DISCRIMINATOR
  );
}

export type WithdrawAllTokensFromTreasuryInstruction<
  TProgram extends string = typeof THE_NYX_WEAVE_PROGRAM_ADDRESS,
  TAccountAdmin extends string | IAccountMeta<string> = string,
  TAccountUsdcMint extends string | IAccountMeta<string> = string,
  TAccountWsolMint extends string | IAccountMeta<string> = string,
  TAccountJitoMint extends string | IAccountMeta<string> = string,
  TAccountAdminUsdcAta extends string | IAccountMeta<string> = string,
  TAccountAdminWsolAta extends string | IAccountMeta<string> = string,
  TAccountAdminJitoAta extends string | IAccountMeta<string> = string,
  TAccountGlobalConfig extends string | IAccountMeta<string> = string,
  TAccountTreasuryVault extends string | IAccountMeta<string> = string,
  TAccountTreasuryVaultUsdcAta extends string | IAccountMeta<string> = string,
  TAccountTreasuryVaultWsolAta extends string | IAccountMeta<string> = string,
  TAccountTreasuryVaultJitoAta extends string | IAccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | IAccountMeta<string> = '11111111111111111111111111111111',
  TAccountTokenProgram extends
    | string
    | IAccountMeta<string> = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountAdmin extends string
        ? WritableSignerAccount<TAccountAdmin> &
            IAccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountUsdcMint extends string
        ? ReadonlyAccount<TAccountUsdcMint>
        : TAccountUsdcMint,
      TAccountWsolMint extends string
        ? ReadonlyAccount<TAccountWsolMint>
        : TAccountWsolMint,
      TAccountJitoMint extends string
        ? ReadonlyAccount<TAccountJitoMint>
        : TAccountJitoMint,
      TAccountAdminUsdcAta extends string
        ? WritableAccount<TAccountAdminUsdcAta>
        : TAccountAdminUsdcAta,
      TAccountAdminWsolAta extends string
        ? WritableAccount<TAccountAdminWsolAta>
        : TAccountAdminWsolAta,
      TAccountAdminJitoAta extends string
        ? WritableAccount<TAccountAdminJitoAta>
        : TAccountAdminJitoAta,
      TAccountGlobalConfig extends string
        ? ReadonlyAccount<TAccountGlobalConfig>
        : TAccountGlobalConfig,
      TAccountTreasuryVault extends string
        ? WritableAccount<TAccountTreasuryVault>
        : TAccountTreasuryVault,
      TAccountTreasuryVaultUsdcAta extends string
        ? WritableAccount<TAccountTreasuryVaultUsdcAta>
        : TAccountTreasuryVaultUsdcAta,
      TAccountTreasuryVaultWsolAta extends string
        ? WritableAccount<TAccountTreasuryVaultWsolAta>
        : TAccountTreasuryVaultWsolAta,
      TAccountTreasuryVaultJitoAta extends string
        ? WritableAccount<TAccountTreasuryVaultJitoAta>
        : TAccountTreasuryVaultJitoAta,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export type WithdrawAllTokensFromTreasuryInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type WithdrawAllTokensFromTreasuryInstructionDataArgs = {};

export function getWithdrawAllTokensFromTreasuryInstructionDataEncoder(): Encoder<WithdrawAllTokensFromTreasuryInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({
      ...value,
      discriminator: WITHDRAW_ALL_TOKENS_FROM_TREASURY_DISCRIMINATOR,
    })
  );
}

export function getWithdrawAllTokensFromTreasuryInstructionDataDecoder(): Decoder<WithdrawAllTokensFromTreasuryInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getWithdrawAllTokensFromTreasuryInstructionDataCodec(): Codec<
  WithdrawAllTokensFromTreasuryInstructionDataArgs,
  WithdrawAllTokensFromTreasuryInstructionData
> {
  return combineCodec(
    getWithdrawAllTokensFromTreasuryInstructionDataEncoder(),
    getWithdrawAllTokensFromTreasuryInstructionDataDecoder()
  );
}

export type WithdrawAllTokensFromTreasuryAsyncInput<
  TAccountAdmin extends string = string,
  TAccountUsdcMint extends string = string,
  TAccountWsolMint extends string = string,
  TAccountJitoMint extends string = string,
  TAccountAdminUsdcAta extends string = string,
  TAccountAdminWsolAta extends string = string,
  TAccountAdminJitoAta extends string = string,
  TAccountGlobalConfig extends string = string,
  TAccountTreasuryVault extends string = string,
  TAccountTreasuryVaultUsdcAta extends string = string,
  TAccountTreasuryVaultWsolAta extends string = string,
  TAccountTreasuryVaultJitoAta extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  admin: TransactionSigner<TAccountAdmin>;
  usdcMint: Address<TAccountUsdcMint>;
  wsolMint: Address<TAccountWsolMint>;
  jitoMint: Address<TAccountJitoMint>;
  adminUsdcAta: Address<TAccountAdminUsdcAta>;
  adminWsolAta: Address<TAccountAdminWsolAta>;
  adminJitoAta: Address<TAccountAdminJitoAta>;
  globalConfig?: Address<TAccountGlobalConfig>;
  treasuryVault?: Address<TAccountTreasuryVault>;
  treasuryVaultUsdcAta: Address<TAccountTreasuryVaultUsdcAta>;
  treasuryVaultWsolAta: Address<TAccountTreasuryVaultWsolAta>;
  treasuryVaultJitoAta: Address<TAccountTreasuryVaultJitoAta>;
  systemProgram?: Address<TAccountSystemProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
};

export async function getWithdrawAllTokensFromTreasuryInstructionAsync<
  TAccountAdmin extends string,
  TAccountUsdcMint extends string,
  TAccountWsolMint extends string,
  TAccountJitoMint extends string,
  TAccountAdminUsdcAta extends string,
  TAccountAdminWsolAta extends string,
  TAccountAdminJitoAta extends string,
  TAccountGlobalConfig extends string,
  TAccountTreasuryVault extends string,
  TAccountTreasuryVaultUsdcAta extends string,
  TAccountTreasuryVaultWsolAta extends string,
  TAccountTreasuryVaultJitoAta extends string,
  TAccountSystemProgram extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof THE_NYX_WEAVE_PROGRAM_ADDRESS,
>(
  input: WithdrawAllTokensFromTreasuryAsyncInput<
    TAccountAdmin,
    TAccountUsdcMint,
    TAccountWsolMint,
    TAccountJitoMint,
    TAccountAdminUsdcAta,
    TAccountAdminWsolAta,
    TAccountAdminJitoAta,
    TAccountGlobalConfig,
    TAccountTreasuryVault,
    TAccountTreasuryVaultUsdcAta,
    TAccountTreasuryVaultWsolAta,
    TAccountTreasuryVaultJitoAta,
    TAccountSystemProgram,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  WithdrawAllTokensFromTreasuryInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountUsdcMint,
    TAccountWsolMint,
    TAccountJitoMint,
    TAccountAdminUsdcAta,
    TAccountAdminWsolAta,
    TAccountAdminJitoAta,
    TAccountGlobalConfig,
    TAccountTreasuryVault,
    TAccountTreasuryVaultUsdcAta,
    TAccountTreasuryVaultWsolAta,
    TAccountTreasuryVaultJitoAta,
    TAccountSystemProgram,
    TAccountTokenProgram
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? THE_NYX_WEAVE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: true },
    usdcMint: { value: input.usdcMint ?? null, isWritable: false },
    wsolMint: { value: input.wsolMint ?? null, isWritable: false },
    jitoMint: { value: input.jitoMint ?? null, isWritable: false },
    adminUsdcAta: { value: input.adminUsdcAta ?? null, isWritable: true },
    adminWsolAta: { value: input.adminWsolAta ?? null, isWritable: true },
    adminJitoAta: { value: input.adminJitoAta ?? null, isWritable: true },
    globalConfig: { value: input.globalConfig ?? null, isWritable: false },
    treasuryVault: { value: input.treasuryVault ?? null, isWritable: true },
    treasuryVaultUsdcAta: {
      value: input.treasuryVaultUsdcAta ?? null,
      isWritable: true,
    },
    treasuryVaultWsolAta: {
      value: input.treasuryVaultWsolAta ?? null,
      isWritable: true,
    },
    treasuryVaultJitoAta: {
      value: input.treasuryVaultJitoAta ?? null,
      isWritable: true,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.globalConfig.value) {
    accounts.globalConfig.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([99, 111, 110, 102, 105, 103])),
        getAddressEncoder().encode(expectAddress(accounts.admin.value)),
      ],
    });
  }
  if (!accounts.treasuryVault.value) {
    accounts.treasuryVault.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            116, 114, 101, 97, 115, 117, 114, 121, 95, 118, 97, 117, 108, 116,
          ])
        ),
        getAddressEncoder().encode(expectAddress(accounts.admin.value)),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.admin),
      getAccountMeta(accounts.usdcMint),
      getAccountMeta(accounts.wsolMint),
      getAccountMeta(accounts.jitoMint),
      getAccountMeta(accounts.adminUsdcAta),
      getAccountMeta(accounts.adminWsolAta),
      getAccountMeta(accounts.adminJitoAta),
      getAccountMeta(accounts.globalConfig),
      getAccountMeta(accounts.treasuryVault),
      getAccountMeta(accounts.treasuryVaultUsdcAta),
      getAccountMeta(accounts.treasuryVaultWsolAta),
      getAccountMeta(accounts.treasuryVaultJitoAta),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.tokenProgram),
    ],
    programAddress,
    data: getWithdrawAllTokensFromTreasuryInstructionDataEncoder().encode({}),
  } as WithdrawAllTokensFromTreasuryInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountUsdcMint,
    TAccountWsolMint,
    TAccountJitoMint,
    TAccountAdminUsdcAta,
    TAccountAdminWsolAta,
    TAccountAdminJitoAta,
    TAccountGlobalConfig,
    TAccountTreasuryVault,
    TAccountTreasuryVaultUsdcAta,
    TAccountTreasuryVaultWsolAta,
    TAccountTreasuryVaultJitoAta,
    TAccountSystemProgram,
    TAccountTokenProgram
  >;

  return instruction;
}

export type WithdrawAllTokensFromTreasuryInput<
  TAccountAdmin extends string = string,
  TAccountUsdcMint extends string = string,
  TAccountWsolMint extends string = string,
  TAccountJitoMint extends string = string,
  TAccountAdminUsdcAta extends string = string,
  TAccountAdminWsolAta extends string = string,
  TAccountAdminJitoAta extends string = string,
  TAccountGlobalConfig extends string = string,
  TAccountTreasuryVault extends string = string,
  TAccountTreasuryVaultUsdcAta extends string = string,
  TAccountTreasuryVaultWsolAta extends string = string,
  TAccountTreasuryVaultJitoAta extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  admin: TransactionSigner<TAccountAdmin>;
  usdcMint: Address<TAccountUsdcMint>;
  wsolMint: Address<TAccountWsolMint>;
  jitoMint: Address<TAccountJitoMint>;
  adminUsdcAta: Address<TAccountAdminUsdcAta>;
  adminWsolAta: Address<TAccountAdminWsolAta>;
  adminJitoAta: Address<TAccountAdminJitoAta>;
  globalConfig: Address<TAccountGlobalConfig>;
  treasuryVault: Address<TAccountTreasuryVault>;
  treasuryVaultUsdcAta: Address<TAccountTreasuryVaultUsdcAta>;
  treasuryVaultWsolAta: Address<TAccountTreasuryVaultWsolAta>;
  treasuryVaultJitoAta: Address<TAccountTreasuryVaultJitoAta>;
  systemProgram?: Address<TAccountSystemProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
};

export function getWithdrawAllTokensFromTreasuryInstruction<
  TAccountAdmin extends string,
  TAccountUsdcMint extends string,
  TAccountWsolMint extends string,
  TAccountJitoMint extends string,
  TAccountAdminUsdcAta extends string,
  TAccountAdminWsolAta extends string,
  TAccountAdminJitoAta extends string,
  TAccountGlobalConfig extends string,
  TAccountTreasuryVault extends string,
  TAccountTreasuryVaultUsdcAta extends string,
  TAccountTreasuryVaultWsolAta extends string,
  TAccountTreasuryVaultJitoAta extends string,
  TAccountSystemProgram extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof THE_NYX_WEAVE_PROGRAM_ADDRESS,
>(
  input: WithdrawAllTokensFromTreasuryInput<
    TAccountAdmin,
    TAccountUsdcMint,
    TAccountWsolMint,
    TAccountJitoMint,
    TAccountAdminUsdcAta,
    TAccountAdminWsolAta,
    TAccountAdminJitoAta,
    TAccountGlobalConfig,
    TAccountTreasuryVault,
    TAccountTreasuryVaultUsdcAta,
    TAccountTreasuryVaultWsolAta,
    TAccountTreasuryVaultJitoAta,
    TAccountSystemProgram,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress }
): WithdrawAllTokensFromTreasuryInstruction<
  TProgramAddress,
  TAccountAdmin,
  TAccountUsdcMint,
  TAccountWsolMint,
  TAccountJitoMint,
  TAccountAdminUsdcAta,
  TAccountAdminWsolAta,
  TAccountAdminJitoAta,
  TAccountGlobalConfig,
  TAccountTreasuryVault,
  TAccountTreasuryVaultUsdcAta,
  TAccountTreasuryVaultWsolAta,
  TAccountTreasuryVaultJitoAta,
  TAccountSystemProgram,
  TAccountTokenProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? THE_NYX_WEAVE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: true },
    usdcMint: { value: input.usdcMint ?? null, isWritable: false },
    wsolMint: { value: input.wsolMint ?? null, isWritable: false },
    jitoMint: { value: input.jitoMint ?? null, isWritable: false },
    adminUsdcAta: { value: input.adminUsdcAta ?? null, isWritable: true },
    adminWsolAta: { value: input.adminWsolAta ?? null, isWritable: true },
    adminJitoAta: { value: input.adminJitoAta ?? null, isWritable: true },
    globalConfig: { value: input.globalConfig ?? null, isWritable: false },
    treasuryVault: { value: input.treasuryVault ?? null, isWritable: true },
    treasuryVaultUsdcAta: {
      value: input.treasuryVaultUsdcAta ?? null,
      isWritable: true,
    },
    treasuryVaultWsolAta: {
      value: input.treasuryVaultWsolAta ?? null,
      isWritable: true,
    },
    treasuryVaultJitoAta: {
      value: input.treasuryVaultJitoAta ?? null,
      isWritable: true,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.admin),
      getAccountMeta(accounts.usdcMint),
      getAccountMeta(accounts.wsolMint),
      getAccountMeta(accounts.jitoMint),
      getAccountMeta(accounts.adminUsdcAta),
      getAccountMeta(accounts.adminWsolAta),
      getAccountMeta(accounts.adminJitoAta),
      getAccountMeta(accounts.globalConfig),
      getAccountMeta(accounts.treasuryVault),
      getAccountMeta(accounts.treasuryVaultUsdcAta),
      getAccountMeta(accounts.treasuryVaultWsolAta),
      getAccountMeta(accounts.treasuryVaultJitoAta),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.tokenProgram),
    ],
    programAddress,
    data: getWithdrawAllTokensFromTreasuryInstructionDataEncoder().encode({}),
  } as WithdrawAllTokensFromTreasuryInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountUsdcMint,
    TAccountWsolMint,
    TAccountJitoMint,
    TAccountAdminUsdcAta,
    TAccountAdminWsolAta,
    TAccountAdminJitoAta,
    TAccountGlobalConfig,
    TAccountTreasuryVault,
    TAccountTreasuryVaultUsdcAta,
    TAccountTreasuryVaultWsolAta,
    TAccountTreasuryVaultJitoAta,
    TAccountSystemProgram,
    TAccountTokenProgram
  >;

  return instruction;
}

export type ParsedWithdrawAllTokensFromTreasuryInstruction<
  TProgram extends string = typeof THE_NYX_WEAVE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    admin: TAccountMetas[0];
    usdcMint: TAccountMetas[1];
    wsolMint: TAccountMetas[2];
    jitoMint: TAccountMetas[3];
    adminUsdcAta: TAccountMetas[4];
    adminWsolAta: TAccountMetas[5];
    adminJitoAta: TAccountMetas[6];
    globalConfig: TAccountMetas[7];
    treasuryVault: TAccountMetas[8];
    treasuryVaultUsdcAta: TAccountMetas[9];
    treasuryVaultWsolAta: TAccountMetas[10];
    treasuryVaultJitoAta: TAccountMetas[11];
    systemProgram: TAccountMetas[12];
    tokenProgram: TAccountMetas[13];
  };
  data: WithdrawAllTokensFromTreasuryInstructionData;
};

export function parseWithdrawAllTokensFromTreasuryInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedWithdrawAllTokensFromTreasuryInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 14) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      admin: getNextAccount(),
      usdcMint: getNextAccount(),
      wsolMint: getNextAccount(),
      jitoMint: getNextAccount(),
      adminUsdcAta: getNextAccount(),
      adminWsolAta: getNextAccount(),
      adminJitoAta: getNextAccount(),
      globalConfig: getNextAccount(),
      treasuryVault: getNextAccount(),
      treasuryVaultUsdcAta: getNextAccount(),
      treasuryVaultWsolAta: getNextAccount(),
      treasuryVaultJitoAta: getNextAccount(),
      systemProgram: getNextAccount(),
      tokenProgram: getNextAccount(),
    },
    data: getWithdrawAllTokensFromTreasuryInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
