[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
the_nyx_weave = "CU8H5mnb1CdmJJiQj5AkowMRFWt7boSwKar6DxS5VUiu"

[programs.localnet]
the_nyx_weave = "CU8H5mnb1CdmJJiQj5AkowMRFWt7boSwKar6DxS5VUiu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "arbitrage-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
