/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  isProgramError,
  type Address,
  type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM,
  type SolanaError,
} from '@solana/kit';
import { THE_NYX_WEAVE_PROGRAM_ADDRESS } from '../programs';

/** UnAuthorizedAdminWithdraw: Unauthorized admin withdraw */
export const THE_NYX_WEAVE_ERROR__UN_AUTHORIZED_ADMIN_WITHDRAW = 0x1770; // 6000
/** InvalidMint: Invalid mint */
export const THE_NYX_WEAVE_ERROR__INVALID_MINT = 0x1771; // 6001

export type TheNyxWeaveError =
  | typeof THE_NYX_WEAVE_ERROR__INVALID_MINT
  | typeof THE_NYX_WEAVE_ERROR__UN_AUTHORIZED_ADMIN_WITHDRAW;

let theNyxWeaveErrorMessages: Record<TheNyxWeaveError, string> | undefined;
if (process.env.NODE_ENV !== 'production') {
  theNyxWeaveErrorMessages = {
    [THE_NYX_WEAVE_ERROR__INVALID_MINT]: `Invalid mint`,
    [THE_NYX_WEAVE_ERROR__UN_AUTHORIZED_ADMIN_WITHDRAW]: `Unauthorized admin withdraw`,
  };
}

export function getTheNyxWeaveErrorMessage(code: TheNyxWeaveError): string {
  if (process.env.NODE_ENV !== 'production') {
    return (theNyxWeaveErrorMessages as Record<TheNyxWeaveError, string>)[code];
  }

  return 'Error message not available in production bundles.';
}

export function isTheNyxWeaveError<TProgramErrorCode extends TheNyxWeaveError>(
  error: unknown,
  transactionMessage: {
    instructions: Record<number, { programAddress: Address }>;
  },
  code?: TProgramErrorCode
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> &
  Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
  return isProgramError<TProgramErrorCode>(
    error,
    transactionMessage,
    THE_NYX_WEAVE_PROGRAM_ADDRESS,
    code
  );
}
