/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  containsBytes,
  fixEncoderSize,
  getBytesEncoder,
  type Address,
  type ReadonlyUint8Array,
} from '@solana/kit';
import {
  type ParsedDepositToTreasuryInstruction,
  type ParsedInitializeInstruction,
  type ParsedWithdrawAllTokensFromTreasuryInstruction,
  type ParsedWithdrawFromTreasuryInstruction,
} from '../instructions';

export const THE_NYX_WEAVE_PROGRAM_ADDRESS =
  '2N1TRSvQTNxH52mhqbgn3XShtXZuPQoaAk1puGw2uJeF' as Address<'2N1TRSvQTNxH52mhqbgn3XShtXZuPQoaAk1puGw2uJeF'>;

export enum TheNyxWeaveAccount {
  GlobalConfig,
  TreasuryVault,
}

export function identifyTheNyxWeaveAccount(
  account: { data: ReadonlyUint8Array } | ReadonlyUint8Array
): TheNyxWeaveAccount {
  const data = 'data' in account ? account.data : account;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([149, 8, 156, 202, 160, 252, 176, 217])
      ),
      0
    )
  ) {
    return TheNyxWeaveAccount.GlobalConfig;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([86, 102, 19, 109, 56, 58, 144, 81])
      ),
      0
    )
  ) {
    return TheNyxWeaveAccount.TreasuryVault;
  }
  throw new Error(
    'The provided account could not be identified as a theNyxWeave account.'
  );
}

export enum TheNyxWeaveInstruction {
  DepositToTreasury,
  Initialize,
  WithdrawAllTokensFromTreasury,
  WithdrawFromTreasury,
}

export function identifyTheNyxWeaveInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array
): TheNyxWeaveInstruction {
  const data = 'data' in instruction ? instruction.data : instruction;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([10, 195, 112, 242, 107, 206, 240, 198])
      ),
      0
    )
  ) {
    return TheNyxWeaveInstruction.DepositToTreasury;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([175, 175, 109, 31, 13, 152, 155, 237])
      ),
      0
    )
  ) {
    return TheNyxWeaveInstruction.Initialize;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([179, 239, 112, 0, 91, 19, 179, 143])
      ),
      0
    )
  ) {
    return TheNyxWeaveInstruction.WithdrawAllTokensFromTreasury;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([0, 164, 86, 76, 56, 72, 12, 170])
      ),
      0
    )
  ) {
    return TheNyxWeaveInstruction.WithdrawFromTreasury;
  }
  throw new Error(
    'The provided instruction could not be identified as a theNyxWeave instruction.'
  );
}

export type ParsedTheNyxWeaveInstruction<
  TProgram extends string = '2N1TRSvQTNxH52mhqbgn3XShtXZuPQoaAk1puGw2uJeF',
> =
  | ({
      instructionType: TheNyxWeaveInstruction.DepositToTreasury;
    } & ParsedDepositToTreasuryInstruction<TProgram>)
  | ({
      instructionType: TheNyxWeaveInstruction.Initialize;
    } & ParsedInitializeInstruction<TProgram>)
  | ({
      instructionType: TheNyxWeaveInstruction.WithdrawAllTokensFromTreasury;
    } & ParsedWithdrawAllTokensFromTreasuryInstruction<TProgram>)
  | ({
      instructionType: TheNyxWeaveInstruction.WithdrawFromTreasury;
    } & ParsedWithdrawFromTreasuryInstruction<TProgram>);
